### PR TITLE
[initial] initial commit for sticky change CSS class

### PR DESCRIPTION
**Pull request by yowainwright**
- [x] Tests
- [ ] Update examples
- [ ] If examples are good, publish
- [ ] else, update with patch version 😔
- **note:** need to stub and test `raf` (in another PR)

### CODE REVIEW

**Comment by yowainwright** [comment]
@DanielRuf lemme know. I will be fast following with a few more PRs.

---

#### Next up 

- Change event
- Move helpers to separate files
- Test manage state statements

**Comment by DanielRuf** [comment]
Will schedule testing for this week.

**Comment by yowainwright** [comment]
#213

**Comment by yowainwright** [comment]
@DanielRuf do you mean code review? ...or write more tests?

**Comment by DanielRuf** [comment]
> @DanielRuf do you mean code review? ...or write more tests?
Code review like you requested =)

**Comment by yowainwright** [comment]
@DanielRuf 🙏

**Comment by DanielRuf** [comment]
Sorry, was busy with other projects. LGTM 👍

**Comment by yowainwright** [comment]
@DanielRuf no worries!!! Hope you were able to enjoy some weekend.

**Pull request merged**
