### PR TITLE
Rosivanov master

### PR DESCRIPTION
**Pull request by yowainwright**

### CODE REVIEW

**Comment by yowainwright** [comment]
@rosivanov I tried to submit the PR with your work/commit however, after rebasing, your specific commit when to me—which was not intentional! 😔

Could you update the **readme** with your github handle in the [thanks](https://github.com/dollarshaveclub/stickybits#thanks) section? ...That way you can get some credit for your hard work. 🙏  Or, if you see anything else you'd like to improve in the readme/gulpfile, please do!

Thanks again!

**Comment by rosivanov** [comment]
@yowainwright Thanks, will wait for npm release!
I think about this issue #66 May be it has sense to add an option in order to add `width` when element is `js-is-sticky` ? What are your thoughts?

**Comment by yowainwright** [comment]
@rosivanov That's a great thought! 

I hesitate to add that as a _option_ because it can be done with CSS. I know that setting the width is important if `position: sticky` isn't used. There should definitely be a note on the [wiki](https://github.com/dollarshaveclub/stickybits/wiki)—at least. 

Maybe we could add a Codepen demo link to the readme?...Thoughts?

**Comment by rosivanov** [comment]
@yowainwright good point, i will try to play around `width` in a pen

**Comment by yowainwright** [comment]
@rosivanov sounds good to me ☺️

**Pull request merged**
