### PR TITLE
fix scroll tracking, fixes #204

### LINKED ISSUE #204: scroll listener not triggered when setting scrollEl
This does not trigger the scroll eventlistener.

There are some inconsistencies when using a selector.

See https://codepen.io/DanielRuf/pen/mpZXXX
https://codepen.io/DanielRuf/pen/ZvdxJL

I'll try to find the cause. So far the calculation is not working as it seems.

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by yowainwright** [comment]
@DanielRuf, There is a lot of good stuff here! 

This update will break [scrollEl](https://github.com/dollarshaveclub/stickybits#custom-scroll-element) I believe. 

Supporting ScrollEl was a tough decision for me to make. It seemed important if Stickybits were to be used in scenarios where `window` may not be defined. Perhaps, I/we should re-think ScrollEl for better support for the standard use-case?!

**Comment by DanielRuf** [comment]
Right. And I guess you mean something like a scroll observer for elements different than `window`. I may have to do some more tests here.

**Comment by DanielRuf** [comment]
How can I test this in the smallest possible example setup? Normally we always have `window` defined when working with webpack based (ES6) projects.

**Comment by yowainwright** [comment]
@DanielRuf I can help with tests! 

I was planning on writing better acceptance tests after I caused @hacknug to have to do some extra work b/c stickybits tests did not catch an issue. 😑

For right now, so me writing tests doesn't block you, just check if `scrollEl` is `window` or `isWin`. I will try to fast follow with better coverage! 

**Here is part of the change that I'm invisioning:**
```javascript
let rAF = function rAFDummy(f) { f() }
if (it.isWin) {
  // your awesome code from your PR
  // rAF = ...
}
```

Let me know if my comment is clear.

Thanks again!!!

**Comment by DanielRuf** [comment]
Thanks for the input. I'll try to find some time today and update the PR with the suggested change.

**Comment by DanielRuf** [comment]
Done ;-)

**Comment by yowainwright** [comment]
@DanielRuf awesome stuff. 

I'm going to do a little clean-up off of this before merging. Great work!

**Comment by DanielRuf** [comment]
I guess I'll have to take a second look as the eventlistener for `scroll` should also work on elements. Watching window here might be too much.

**Pull request merged**
