### PR TITLE
Renames second constructor parameter to config and gives it default value ES6-style

### PR DESCRIPTION
**Pull request by alexey-m-ukolov**

### CODE REVIEW

**Comment by alexey-m-ukolov** [comment]
I've just checked - it adds 3 bytes to the minified version. Are you sure that this is a right trade-off?

**Comment by yowainwright** [comment]
@alexey-m-ukolov I saw you re-opened this PR. If you'd like to do this:

```
constructor (target, options = {}) {
  const o = typeof options !== 'undefined' ? options : {}
```
I'll approve. ...Or replace `options` with `config`—I'm indifferent at that point. 

----

The reason I'm against a default param value is what happens to the code after bundling (helper code is added that is much larger than  const o = typeof options !== 'undefined' ? options : {}` so that's what it's written how it is).

**Comment by yowainwright** [comment]
@alexey-m-ukolov if we're going to de-structure, we should do it all! If we can get that at only 3 extra bytes, I'm in. 💯

**Comment by alexey-m-ukolov** [comment]
> If you'd like to do this:
> ```
> constructor (target, options = {}) {
>   const o = typeof options !== 'undefined' ? options : {}
> ```

Sorry, I don't quite get what you mean...

> helper code is added that is much larger than `const o = typeof options !== 'undefined' ? options : {}` so that's what it's written how it is

`config = {}` is bundles to this:
```
if (config === void 0) {
    config = {};
}
```
It's virtually the same.

**Comment by alexey-m-ukolov** [comment]
> Or replace options with config—I'm indifferent at that point.
Yeah, me too :)
I like _config_ because it's something a user passes to the library, but _options_ are good to.

**Comment by yowainwright** [comment]
@alexey-m-ukolov this is good to know! 

> config = {} is bundles to this:
> ```javascript
>  if (config === void 0) {
>    config = {};
> }
> ```

~Thanks for the insight into Rollup's bundling optimizations (so cool).

----

## To merge this

Do

```javascript

constructor (target, options) {
  const o = typeof options !== 'undefined' ? options : {}

```

And I'll approve. 

I prefer "options" because then `o` still makes sense.

**Comment by yowainwright** [comment]
@alexey-m-ukolov if you would like to try a PR with a fully destructured `options/config` after this PR is merge...to look at the bundle size, I would be happy to review.

**Comment by alexey-m-ukolov** [comment]
> Do
> ```
> constructor (target, options) {
>   const o = typeof options !== 'undefined' ? options : {}
> ```
> And I'll approve.
But that's just renaming `obj` parameter to `options`, it's not worth the trouble...

> if you would like to try a PR with a fully destructured options/config after this PR is merge...to look at the bundle size, I would be happy to review.
What do you mean by _fully destructured_?
Something like this: `constructor (target, {optionA, optionB = 'default'})`?
If so, I don't think this will improve readability - there are too many options for that.

Whole point of this PR is to bring idiomatic ES6 to the constructor - if library uses classes, then it's using ES6, then it should be written in the ES6 style whenever possible to be consistent. Here it brings 3 additional bytes (which will be won back after removing return from the constructor), so using old syntax is not justified imo.

**Pull request closed without merging**
