### PR TITLE
[tests] use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
https://circleci.com/blog/sudo-circleci-make-me-a-sandwich/

### CODE REVIEW

**Comment by yowainwright** [comment]
@danielruf I will look shortly. I love that you’re doing ci stuff!

**Comment by yowainwright** [comment]
@DanielRuf I'm all about adding this feature but I want to ensure it works within this PR! 😊

I really appreciate this! 🙏

**Comment by DanielRuf** [comment]
How can I make sure that it works with the current CircleCI implementation?

**Comment by yowainwright** [comment]
If you can get this working, a lot of code can be removed 🤤.

```
restore_cache: &restore_cache
  restore_cache:
    keys:
      - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

save_cache: &save_cache
  save_cache:
      key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
      paths:
        - node_modules
```
Otherwise, the code above does the similar thing as `npm ci`.

**Comment by yowainwright** [comment]
@DanielRuf I will be writing a blog post on why I'm loving CircleCi 2. Which will hopefully give context into the change. As far as using `npm ci`, I look forward to your findings.

**Comment by DanielRuf** [comment]
Still no CircleCI tests on PRs =( Please let me know how I can proceed here.

**Comment by DanielRuf** [comment]
See https://circleci.com/docs/1.0/fork-pr-builds/

**Comment by yowainwright** [comment]
@DanielRuf on it—shortly.

**Comment by yowainwright** [comment]
@DanielRuf, Stickbits uses CircleCi 2.0 for reference. 

...I’m still going to follow up on the comment above.

**Comment by DanielRuf** [comment]
27s+ vs 12s (+13s)

circleci com_gh_danielruf_stickybits_6


circleci com_gh_dollarshaveclub_stickybits_32 1

**Comment by yowainwright** [comment]
project_settings_-_dollarshaveclub_stickybits_-_circleci

**Comment by DanielRuf** [comment]
All tests are green =)

**Comment by yowainwright** [comment]
@DanielRuf What happens when this line is removed `sudo npm install -g npm@latest`?

**Comment by DanielRuf** [comment]
> @DanielRuf What happens when this line is removed sudo npm install -g npm@latest

This line ensures that the latest npm version is installed which ships with the ci command (shipped with Node.js 9 and newer).

**Comment by DanielRuf** [comment]
See http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

**Comment by DanielRuf** [comment]
https://github.com/npm/npm/releases/tag/v5.7.1

We can never reliably know which version is used by CI solution providers.

**Comment by yowainwright** [comment]
@DanielRuf please try my request. 

If `sudo npm install -g npm@latest` is needed to run `npm ci` then I don't want to add `npm ci` right now.

**Comment by DanielRuf** [comment]
Not sure why this should be problematic in general.

Without this line it does not work, see https://circleci.com/gh/DanielRuf/stickybits/9

**Comment by DanielRuf** [comment]
On CircleCI you need sudo unlike on TravisCI in most cases.

**Comment by yowainwright** [comment]
@DanielRuf on CircleCi, sudo, thanks to your check, seems to be needed to use `npm ci` but it is not needed generally. 

In regards to speed, CircleCi 2.0 (what Stickybits uses) allows for running multiple jobs at once—so **maybe** `sudo npm install -g npm@latest && npm ci` is 3 seconds faster but using multiple jobs sped up the CI time using Circle to about 10 seconds compared to using Travis which was about 7 minutes. 

## CircleCi
circleci

## Travis
build__720_-_dollarshaveclub_stickybits_-_travis_ci

So the big win (switching to CircleCi) is worth it to me b/c that is minutes but using `npm ci` is not currently because it is only seconds and requires Stickybits to install the latest npm version.

**Comment by DanielRuf** [comment]
Not exactly, sudo is needed in this environment to upgrade the globally installed npm version.

TravisCI also supports multiple jobs and has the test matrix feature.

Keep in mind that more developers use Travis which uses specific shared instances by default and the VM need some time to boot and are a bit slower.

In general it is about `npm test` with the right commands for others.

7 minutes sounds way off and too much. We have ~250 unit tests at ZURB Foundation, switched to puppeteer and have around 1-2 minutes for everything (we use a specific Travis config to ensure better test performance).

In production no one runs `npm tests`, it is for the developers, contributors and CI to get faster and expected results (no revalidation of package-lock.json, no output similar to `npm ls`, proper cache usage, immutable lockfile, ...).

**Comment by yowainwright** [comment]
@DanielRuf really great stuff [here](https://github.com/zurb/foundation-sites/commit/9242a2c971111c241d92522fb1e7aafd249cf800). 

When CI works w/o `sudo npm install -g npm@latest`, we'll merge it.

**Comment by DanielRuf** [comment]
Also keep in mind that CircleCI has some cache (TravisCI does not provide/use this by default) and that is uses the checksum if the package.json file but not the lockfile.

**Comment by yowainwright** [comment]
@DanielRuf I switched to node 10 but straight node 10 comes with npm 5.6 (I think). Hopefully, in the next week or 2 we can get this update in.

**Comment by yowainwright** [comment]
@DanielRuf I think with the version of node 10 that is now default, `npm ci` might work! ...?

**Comment by DanielRuf** [comment]
What is the default with Node.js 10?

**Comment by yowainwright** [comment]
@DanielRuf for me locally (using nvm), I think it is 10.4.1.

**Comment by yowainwright** [comment]
I am happy to try if it is a time issue for you.

**Comment by DanielRuf** [comment]
> What is the default with Node.js 10?

What exactly did you mean with `default`?

Node.js 10 uses npm 6 but `npm ci` is (never) not used by default.

**Comment by yowainwright** [comment]
This conversation is going in circles. 😊

Do you want to see if this PR works now?

**Comment by yowainwright** [comment]
@DanielRuf Awesome!!!! 

Thank you for your work on Stickybits and across all OSS. 🙏

**Pull request merged**
