### PR TITLE
Fix for - Sticky Classes aren't toggling properly if scrolltop not 0 on anchor load #100

### PR DESCRIPTION
**Pull request by ajithbhat**
I had the same issue but just calculating the offset of the parent wasn't enough in my case. I had to traverse the offsetParent upto the top level of the DOM. So I ended up creating a function to calculate offsetTop:

var getOffsetTop = function getOffsetTop(elem) {
  var offsetTop = 0;
  do {
    if (!isNaN(elem.offsetTop)) {
      offsetTop += elem.offsetTop;
    }
  } while (elem = elem.offsetParent);
  return offsetTop;
};
And use the above method in computeScrollOffsets function:

Stickybits.prototype.computeScrollOffsets = function computeScrollOffsets(item) {
  var it = item;
  var p = it.props;
  var parent = it.parent;
  var iw = it.isWin;
  var scrollElOffset = 0;
//  let stickyStart = parent.getBoundingClientRect().top
  var stickyStart = getOffsetTop(parent); 
  if (!iw && p.positionVal === 'fixed') {
//    scrollElOffset = p.scrollEl.getBoundingClientRect().top
    scrollElOffset = getOffsetTop(p.scrollEl); 

//    stickyStart = parent.getBoundingClientRect().top - scrollElOffset
    stickyStart = stickyStart - scrollElOffset;
  }
  it.offset = scrollElOffset + p.stickyBitStickyOffset;
  it.stickyStart = stickyStart - it.offset;
  it.stickyStop = stickyStart + parent.offsetHeight - (it.el.offsetHeight + it.offset);
  return it;
};
A new release with these changes would be helpful.
TIA

### CODE REVIEW

**Comment by yowainwright** [comment]
@ajithbhat thanks for the PR. 🙏 

The code in this PR doesn't solve the issue being discussed [here](https://github.com/dollarshaveclub/stickybits/issues/100) as I read it. The issue, as I read the comments, suggests that on a single page app or when a user clicks an anchor (`<a href="#anchor">`) that that throws off the Stickybits classes. 

~Thanks again!

**Comment by ethanmuller** [comment]
For what it's worth, this fork fixes the issue for me! I've been running into an issue that sounds like exactly what #100 is describing. FWIW, this is only happening in Chrome, not Safari.

I put together test cases to help illustrate the issue, and how it fixes it:

**Stickybits 3.3.1 (issue present):** https://s.codepen.io/ethanmuller/debug/zjwMEa
**ajithbhat's fork (issue fixed):** https://s.codepen.io/ethanmuller/debug/qYjOrM

Please let me know if there's a better place to post this, or if you need any more details from me.

Thanks for your work!

**Comment by yowainwright** [comment]
@ajithbhat @ethanmuller darnit, yet again—maybe I missed some awesomeness! I will look at this closer today. 

@ethanmuller thanks for asking me to re-look at this! 

@ajithbhat sorry if my initial response was my misunderstanding.

**Comment by ajithbhat** [comment]
No worries, let me know if my solution works & I can pull the latest changes from Master branch & re-initiate my PR.

**Comment by yowainwright** [comment]
@ajithbhat update please and THANK YOU! 🙏

Great work!

**Comment by yowainwright** [comment]
@ajithbhat Thanks

This worked for me (es6). 
```javascript
getOffsetTop (el) {
    let offsetTop = 0
    do offsetTop = el.offsetTop + offsetTop
    while (el = el.offsetParent)
    return offsetTop
}
```
Could you please run`npm run lint` to ensure that linting is okay?

View more [here](https://codepen.io/yowainwright/pen/odGNqy/).

**Comment by ajithbhat** [comment]
Thanks @yowainwright for the review. I have now made requested changes & pushed up the changes. But, I think we should have a isNan check for el.offsetTop before we do offsetTop = el.offsetTop + offsetTop. This is in case if we have el.offsetTop as undefined.

Let me know your thoughts.

**Comment by yowainwright** [comment]
@ajithbhat `offsetTop` is supported in all browsers Stickybits supports and will always return a number. I don't think the statement is needed. 

That said, you've already foreseen something that I didn't once! 😜🙏

Thank you!!!

**Pull request merged**
