### PR TITLE
Allow scrollEl parameter to accept a DOM element in addition to a selector string.

### LINKED ISSUE #340: scrollEl accepting only a selector makes it difficult to use stickybits with libraries like react
React has a concept of `refs` which can be used to work with javascript libraries that depend on DOM elements being more reliably available.

The `scrollEl` parameter in stickybits currently takes on a selector string, which makes it impossible to point to a specific rendered element in React and be confident that element isn't going to change out from under stickybits.

How would you feel about updating `scrollEl` to accept either a selector _or_ an element to make it easier to use with React?

### PR DESCRIPTION
**Pull request by cmalven**
Intended to handle both use in React – where targeting elements based on a selector is risky – and other situations where targeting a specific element more directly is preferable.

Fixes #340

### CODE REVIEW

**Comment by yowainwright** [comment]
@cmalven could you provide a feature version bump (`3.4.0` in the `package.json`) and build `npm run build`?

—Thanks!

**Comment by yowainwright** [comment]
@cmalven thanks! Thanks for the turn around time. 🎉

**Comment by cmalven** [comment]
@yowainwright Let me know if there's anything I can do to help get those Codepens updated.

**Comment by yowainwright** [comment]
@cmalven do I need to update something?

**Comment by cmalven** [comment]
@yowainwright 

> I will publish after the Codepens have been updated which is manual.

Lead me to believe that someone had to update related Codepens before this work could be published.

**Comment by yowainwright** [comment]
@cmalven okay. I published [a while ago](https://www.npmjs.com/package/stickybits) (25 days). I do need to update the CodePens for 3.4.1 though. Thanks for pointing that out!

**Comment by cmalven** [comment]
@yowainwright Ah, my mistake. Looking at the latest README it didn't look like the docs around `Custom Scroll Element` had changed as I expected them to in https://github.com/dollarshaveclub/stickybits/pull/341/files so I assumed this hadn't been published yet.

Sorry for the confusion.

**Pull request merged**
