### PR TITLE
use babel-preset-env

### PR DESCRIPTION
**Pull request by DanielRuf**
also remove bower and cleanup .npmignore

### CODE REVIEW

**Comment by DanielRuf** [comment]
If needed we should also provide the browserlist values for the browsers that should be supported.

**Comment by yowainwright** [comment]
@DanielRuf oops, sorry about the first comment. I didn't see your comment. 😬 

...Respond when you get a chance to add browserlist values. 

~Thanks 🙏

**Comment by DanielRuf** [comment]
No problem.

> ...Respond when you get a chance to add browserlist values
Ok.

**Comment by yowainwright** [comment]
@DanielRuf https://github.com/dollarshaveclub/stickybits#browser-compatibility 😬  ...whenever you have time. 👌

**Comment by DanielRuf** [comment]
Ok. I'll try to do it today.

**Comment by yowainwright** [comment]
@DanielRuf no rush at all!

**Comment by DanielRuf** [comment]
I guess this config should be sufficient.

**Pull request merged**
