### PR TITLE
Constructor readability improvements

### PR DESCRIPTION
**Pull request by alexey-m-ukolov**
Not sure what to say here :)
In my opinion now it's much more readable and coherent - ES6 syntax is used instead of old ways (ex. empty object as a default value for config param).

I've also moved `this.isWin` calculation where it should be. Previously it was calculated and reset on each target element instantiation.

Method *addInstance* renamed to *makeInstance* since it returns new instance and not adds it to anything.

The one change that is breaking is that *definePosition* does not checks this.props.useFixed, instead this check runs in *makeProps*. I think this is quite alright since this method is essentially private and keeping this logic requires more logic and/or hacks. But if you are not comfortable with it, I'll revert this change.

### CODE REVIEW

**Comment by yowainwright** [comment]
@alexey-m-ukolov Thanks for your thoughtfulness in this PR! However, the diff is too large and is a mix of opinion based changes and changes that may optimize stickybits. 

As Stickybits supports many customers, these changes aren’t mergable as is—in 1 PR. Please close this PR and make a PRs that articulate your PR comments clearly—‘changes variable name in X’, ‘move isWin’, etc. 

Please, no breaking changes. I’m most curious about the isWin optimization. 

Thanks for your time and this PR @alexey-m-ukolov! I hope we can implement a lot of you ideas in other smaller and clearer PRs! 💪

I will be around to review PRs over this weekend.

~Thanks again!

**Comment by alexey-m-ukolov** [comment]
OK, I see your point. It's not gonna be easy though - most of the proposed changes are closely coupled. But let's start with the smaller stuff.

**Comment by alexey-m-ukolov** [comment]
Just to be clear - I see some potential bugs in the library, but to be sure I have to be able to understand what's going on in the code. Currently it's hard to read and understand because of misleading or obfuscated names and general clutter here and there.

Please don't take this critique personally, we've all been there. And with this PR we kinda traded roles - I understand perfectly well what's going on in it and what my intentions were, but since I constructed it poorly _you_ can't.

**Comment by yowainwright** [comment]
@alexey-m-ukolov, I hope you do submit smaller PRs following this PR! I think you can do it based on my initial review of this PR. 

----

> A large PR from a non-owner/maintainer will not get merged without specific test updates, bug reports, examples, etc because it's risky! My comment above doesn't have to do with my feelings. If readable and maintainable PRs that make Stickybits better are submitted, they will get merged. 

---

Thanks, again! I appreciated this previous [commit](https://github.com/dollarshaveclub/stickybits/commit/2916f7a4cbe6dd2d30675b4f9c5ac81b58ace8a3) and the work you put into this PR. I hope you'll continue to contribute. 👍

**Pull request closed without merging**
